/*==============================================================================
                Copyright (c) 2003-2005 UGS Corporation
                   Unpublished - All Rights Reserved
 ==============================================================================*/

/*
    File Description:

    The header file that defines the export symbols for the B library
*/

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use B_API, not BEXPORT */

#define B_API BEXPORT

/* Support BOMEXPORT for autogenerated schema/pif code only */

#if IPLIB==libb || IPLIB==libcore
#   if defined(__lint)
#       define BEXPORT       __export(a)
#       define BGLOBAL       extern __global(a)
#       define BPRIVATE      extern __private(a)
#   elif defined(_WIN32)
#       define BEXPORT       __declspec(dllexport)
#       define BGLOBAL       extern __declspec(dllexport)
#       define BPRIVATE      extern
#   else
#       define BEXPORT
#       define BGLOBAL       extern
#       define BPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define BEXPORT       __export(a)
#       define BGLOBAL       extern __global(a)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define BEXPORT      __declspec(dllimport)
#       define BGLOBAL       extern __declspec(dllimport)
#   else
#       define BEXPORT
#       define BGLOBAL       extern
#   endif
#endif

